apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cluster-operator
  namespace: system
  labels:
    control-plane: redis-cluster-operator
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: redis-cluster-operator
    app.kubernetes.io/part-of: redis-cluster-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: redis-cluster-operator
  replicas: 2
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: redis-cluster-operator
      labels:
        control-plane: redis-cluster-operator
    spec:
      serviceAccountName: redis-cluster-operator

      containers:
        - name: redis-cluster-operator
          # Replace this with the built image name
          image: docker.io/dinesh-murugiah/rediscluster-operator:4263e8d-dirty
          command:
          - rediscluster-operator
          args:
          #- --zap-level=debug
          - --rename-command-path=/etc/redisconf
          - --rename-command-file=redis.conf
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "redis-cluster-operator"
          volumeMounts:
            - name: redisconf
              mountPath: /etc/redisconf
      volumes:
        - name: redisconf
          configMap:
            name: redis-admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-admin
  namespace: system
data:
  redis.conf: |-
    rename-command CONFIG lni07z1p
    rename-command BGSAVE pp14qluk
    rename-command DEBUG 8a4insyv
    rename-command SAVE 6on30p6z
    rename-command SHUTDOWN dvui0opr
    rename-command SLAVEOF xwxvcw36
    rename-command BGREWRITEAOF www07fko
