---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redis-kun-redis-kun-v1alpha1-distributedrediscluster
  failurePolicy: Fail
  name: mdistributedrediscluster.kb.io
  rules:
  - apiGroups:
    - redis.kun.redis.kun
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - distributedredisclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redis-kun-redis-kun-v1alpha1-distributedrediscluster
  failurePolicy: Fail
  name: vdistributedrediscluster.kb.io
  rules:
  - apiGroups:
    - redis.kun.redis.kun
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - distributedredisclusters
  sideEffects: None
