# permissions for end users to view distributedredisclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: distributedrediscluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: redis-cluster-operator
    app.kubernetes.io/part-of: redis-cluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: distributedrediscluster-viewer-role
rules:
- apiGroups:
  - redis.kun.redis.kun
  resources:
  - distributedredisclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.kun.redis.kun
  resources:
  - distributedredisclusters/status
  verbs:
  - get
