---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - redis.kun
  resources:
  - distributedredisclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.kun
  resources:
  - distributedredisclusters/finalizers
  verbs:
  - update
- apiGroups:
  - redis.kun
  resources:
  - distributedredisclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redis.kun
  resources:
  - redisclusterbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.kun
  resources:
  - redisclusterbackups/finalizers
  verbs:
  - update
- apiGroups:
  - redis.kun
  resources:
  - redisclusterbackups/status
  verbs:
  - get
  - patch
  - update
